version: '3.1'

services:

  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - "5435:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
